### ISSUE TITLE
Add a next-night email CTA to the waiting room

### ISSUE THREAD

**Issue by marwaneazzouzi** [getamourette/amourette-webapp#136]
## Goal

Give waiting participants a simple second action: optionally enter their email address to hear about future Amourette nights, without introducing PWA installation, Web Push, an account requirement, or a second subscription model.

## Context

The Safari-to-PWA investigation in #119 showed that reliable anonymous identity continuity would require too much installation and authentication friction for a live bar experience. PWA and Web Push are deferred. Realtime remains the in-browser mechanism for the current night; email is only for future-night announcements.

#105 establishes `public.email_subscriptions` as the single source of truth for landing, room-popup, and waiting-room consent. The waiting-room CTA must write the current anonymous Auth user's row with source `waiting_room`; it must not write legacy `profile_private` email fields or create another consent record.

## Scope

- add a secondary waiting-room CTA that clearly offers future Amourette night announcements by email;
- reuse the canonical subscription and consent behavior introduced by #105;
- record explicit consent with the current copy version, locale, timestamp, and source `waiting_room`;
- suppress the CTA when the current user is already subscribed or explicitly dismissed the relevant prompt;
- define deterministic coordination between the waiting-room CTA and the existing timed room popup so both cannot appear or ask for the same consent redundantly;
- preserve the full anonymous waiting-room and Realtime flow when the CTA is ignored or declined;
- keep marketing consent separate from authentication: submitting an email must not create, convert, recover, or link an Auth identity;
- provide localized and accessible success, error, duplicate, and already-subscribed states;
- retain privacy boundaries: email remains owner-private and is never exposed through room queries or Realtime.

## Dependencies and boundaries

- depends on #105 for the canonical store and shared capture behavior;
- coordinates with #64's subscription-management and unsubscribe semantics;
- does not implement public unsubscribe tokens, email delivery, PWA installation, Web Push, or native-app identity transfer;
- #63 consumes the resulting active subscription through the canonical store.

Recommended delivery order: #105 → #64 → #136 → #63.

## Acceptance criteria

- the waiting room offers one clear optional email action for future-night announcements;
- submission creates or updates only the current user's canonical subscription row;
- the stored source is `waiting_room`;
- an already-subscribed person is not prompted again;
- the waiting-room CTA and existing email popup never compete or collect duplicate consent;
- declining or dismissing has no effect on check-in, waiting, room launch, or Realtime;
- email submission remains marketing consent only and does not change `auth.uid()` or account status;
- email stays owner-private under RLS;
- EN, FR, and ES behavior and representative mobile states are covered.
